"""add notes to appointment

Revision ID: add964e5a789
Revises: 72d2a5183c89
Create Date: 2024-09-08 15:58:51.219427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add964e5a789'
down_revision = '72d2a5183c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_table', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_table', 'notes')
    # ### end Alembic commands ###
