"""trying the fix timezones

Revision ID: 18a5e54f11eb
Revises: add964e5a789
Create Date: 2024-09-08 17:30:37.076830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a5e54f11eb'
down_revision = 'add964e5a789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
