"""init

Revision ID: 72d2a5183c89
Revises: 
Create Date: 2024-09-08 12:45:44.465341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d2a5183c89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_interaction_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interaction_description', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_substitution_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('side_effect_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_table('medication_table',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('salt_composition', sa.String(length=300), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('habit_forming', sa.Boolean(), nullable=True),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('patient_table',
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('deceased', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact')
    )
    op.create_table('practitioner_table',
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('speciality', sa.Enum('GENERAL_PRACTICE', 'FAMILY_MEDICINE', 'INTERNAL_MEDICINE', 'OBSTETRICS_AND_GYNECOLOGY', 'GYNECOLOGY', 'MATERNAL_FETAL_MEDICINE', 'ONCOLOGY', 'MEDICAL_ONCOLOGY', 'SURGICAL_ONCOLOGY', 'PEDIATRICS', 'NEONATOLOGY', 'PSYCHIATRY', 'CHILD_AND_ADOLESCENT_PSYCHIATRY', 'GERIATRIC_PSYCHIATRY', 'SURGERY', 'UROLOGY', 'ENT', 'NEUROLOGY', 'CARDIOLOGY', 'INTERVENTIONAL_CARDIOLOGY', 'ELECTROPHYSIOLOGY', 'GASTROENTEROLOGY', 'HEPATOLOGY', 'ONCOLOGY_AND_ENDOCRINOLOGY', 'ENDOCRINOLOGY', 'DIABETES_AND_METABOLISM', 'NEPHROLOGY', 'RHEUMATOLOGY', 'NUTRITION', 'NEUROSURGERY', 'DERMATOLOGY', 'PULMONOLOGY', 'CRITICAL_CARE_MEDICINE', 'RADIATION_ONCOLOGY', 'NEUROLOGY_AND_NEUROSURGERY', 'RHEUMATOLOGY_AND_ENDOCRINOLOGY', 'OPHTHALMOLOGY', 'ORTHOPEDICS', 'SPORTS_MEDICINE', 'PLASTIC_SURGERY', 'HAND_SURGERY', 'VASCULAR_SURGERY', 'TRAUMA_SURGERY', 'THORACIC_SURGERY', 'CARDIOTHORACIC_SURGERY', 'PEDIATRIC_SURGERY', 'GERIATRIC_MEDICINE', 'PAIN_MEDICINE', 'ANESTHESIOLOGY', 'INTERVENTIONAL_RADIOLOGY', 'DIAGNOSTIC_RADIOLOGY', 'EMERGENCY_MEDICINE', 'INFECTIOUS_DISEASES', 'ALLERGY_AND_IMMUNOLOGY', 'PHYSICAL_MEDICINE_AND_REHABILITATION', 'PALLIATIVE_MEDICINE', 'SLEEP_MEDICINE', 'OCCUPATIONAL_MEDICINE', 'ADDICTION_MEDICINE', 'HEMATOLOGY', 'IMMUNOLOGY', 'TRANSFUSION_MEDICINE', name='speciality'), nullable=False),
    sa.Column('deceased', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('exp', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_refresh_token'), 'refresh_token', ['refresh_token'], unique=True)
    op.create_table('appointment_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BOOKED', 'PROPOSED', 'ARRIVED', 'FULFILLED', 'CANCELLED', 'NO_SHOW', 'ENTERED_IN_ERROR', 'CHECKED_IN', 'WAITLIST', name='appointmentstatus'), nullable=False),
    sa.Column('speciality', sa.Enum('GENERAL_PRACTICE', 'FAMILY_MEDICINE', 'INTERNAL_MEDICINE', 'OBSTETRICS_AND_GYNECOLOGY', 'GYNECOLOGY', 'MATERNAL_FETAL_MEDICINE', 'ONCOLOGY', 'MEDICAL_ONCOLOGY', 'SURGICAL_ONCOLOGY', 'PEDIATRICS', 'NEONATOLOGY', 'PSYCHIATRY', 'CHILD_AND_ADOLESCENT_PSYCHIATRY', 'GERIATRIC_PSYCHIATRY', 'SURGERY', 'UROLOGY', 'ENT', 'NEUROLOGY', 'CARDIOLOGY', 'INTERVENTIONAL_CARDIOLOGY', 'ELECTROPHYSIOLOGY', 'GASTROENTEROLOGY', 'HEPATOLOGY', 'ONCOLOGY_AND_ENDOCRINOLOGY', 'ENDOCRINOLOGY', 'DIABETES_AND_METABOLISM', 'NEPHROLOGY', 'RHEUMATOLOGY', 'NUTRITION', 'NEUROSURGERY', 'DERMATOLOGY', 'PULMONOLOGY', 'CRITICAL_CARE_MEDICINE', 'RADIATION_ONCOLOGY', 'NEUROLOGY_AND_NEUROSURGERY', 'RHEUMATOLOGY_AND_ENDOCRINOLOGY', 'OPHTHALMOLOGY', 'ORTHOPEDICS', 'SPORTS_MEDICINE', 'PLASTIC_SURGERY', 'HAND_SURGERY', 'VASCULAR_SURGERY', 'TRAUMA_SURGERY', 'THORACIC_SURGERY', 'CARDIOTHORACIC_SURGERY', 'PEDIATRIC_SURGERY', 'GERIATRIC_MEDICINE', 'PAIN_MEDICINE', 'ANESTHESIOLOGY', 'INTERVENTIONAL_RADIOLOGY', 'DIAGNOSTIC_RADIOLOGY', 'EMERGENCY_MEDICINE', 'INFECTIOUS_DISEASES', 'ALLERGY_AND_IMMUNOLOGY', 'PHYSICAL_MEDICINE_AND_REHABILITATION', 'PALLIATIVE_MEDICINE', 'SLEEP_MEDICINE', 'OCCUPATIONAL_MEDICINE', 'ADDICTION_MEDICINE', 'HEMATOLOGY', 'IMMUNOLOGY', 'TRANSFUSION_MEDICINE', name='speciality'), nullable=False),
    sa.Column('practitioner_id', sa.String(length=10), nullable=False),
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_table.contact'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner_table.contact'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_drug_interaction_association',
    sa.Column('medication_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('drug_interaction_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['drug_interaction_id'], ['drug_interaction_table.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_table.id'], ),
    sa.PrimaryKeyConstraint('medication_id', 'drug_interaction_id')
    )
    op.create_table('medication_side_effect_association',
    sa.Column('medication_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('side_effect_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_table.id'], ),
    sa.ForeignKeyConstraint(['side_effect_id'], ['side_effect_table.id'], ),
    sa.PrimaryKeyConstraint('medication_id', 'side_effect_id')
    )
    op.create_table('medication_substitution_association',
    sa.Column('medication_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('substitution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_table.id'], ),
    sa.ForeignKeyConstraint(['substitution_id'], ['drug_substitution_table.id'], ),
    sa.PrimaryKeyConstraint('medication_id', 'substitution_id')
    )
    op.create_table('report_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('report_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_table.contact'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('practitioner_id', sa.String(length=10), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_table.contact'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner_table.contact'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_parameter_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('results', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('ranges', sa.String(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinical_status', sa.Enum('ACTIVE', 'RECURRENCE', 'RELAPSE', 'INACTIVE', 'REMISSION', 'RESOLVED', 'UNKNOWN', name='clinicalstatus'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'moderate', 'high', name='severity'), nullable=False),
    sa.Column('body_site', sa.Enum('HEAD', 'NECK', 'CHEST', 'ABDOMEN', 'BACK', 'PELVIS', 'ARMS', 'LEGS', 'HANDS', 'FEET', 'SHOULDERS', 'KNEES', 'ELBOWS', 'JOINTS', 'SKIN', 'ORAL', 'EYES', 'EARS', 'NOSE', 'THROAT', 'LUNGS', 'HEART', 'LIVER', 'KIDNEYS', 'BLADDER', 'BOWELS', 'PROSTATE', 'OVARIES', 'UTERUS', 'TESTICLES', 'OTHER', name='bodysite'), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_prescription_association',
    sa.Column('medication_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication_table.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription_table.id'], ),
    sa.PrimaryKeyConstraint('medication_id', 'prescription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_prescription_association')
    op.drop_table('condition_table')
    op.drop_table('report_parameter_table')
    op.drop_table('prescription_table')
    op.drop_table('diagnosis_table')
    op.drop_table('report_table')
    op.drop_table('medication_substitution_association')
    op.drop_table('medication_side_effect_association')
    op.drop_table('medication_drug_interaction_association')
    op.drop_table('appointment_table')
    op.drop_index(op.f('ix_refresh_token_refresh_token'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('practitioner_table')
    op.drop_table('patient_table')
    op.drop_table('medication_table')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('side_effect_table')
    op.drop_table('manufacturer_table')
    op.drop_table('drug_substitution_table')
    op.drop_table('drug_interaction_table')
    # ### end Alembic commands ###
