import {Medicine} from "@/types/MedicationTypes";
import {Prescription} from "@/types/AppointmentTypes";

export const appointments = [
    {
        patientName: "Lindsay Walton",
        appointmentDate: "2024-09-03",
        appointmentTime: "10:00 AM",
        patientContact: "9827131123",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient experiencing mild headaches.",
    },
    {
        patientName: "Evan Peters",
        appointmentDate: "2024-09-03",
        appointmentTime: "11:00 AM",
        patientContact: "9827132143",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient's blood pressure needs monitoring.",
    },
    {
        patientName: "Mia Rodriguez",
        appointmentDate: "2024-09-03",
        appointmentTime: "12:00 PM",
        patientContact: "9827133153",
        appointmentType: "Consultation",
        status: "Rescheduled",
        doctorNotes: "Patient is complaining of joint pain.",
    },
    {
        patientName: "Oliver Smith",
        appointmentDate: "2024-09-03",
        appointmentTime: "01:00 PM",
        patientContact: "9827134163",
        appointmentType: "Consultation",
        status: "Completed",
        doctorNotes: "Prescribed medication for allergies.",
    },
    {
        patientName: "Sophia Johnson",
        appointmentDate: "2024-09-03",
        appointmentTime: "02:00 PM",
        patientContact: "9827135173",
        appointmentType: "Check-up",
        status: "Scheduled",
        doctorNotes: "Routine check-up.",
    },
    {
        patientName: "Jackson Lee",
        appointmentDate: "2024-09-03",
        appointmentTime: "03:00 PM",
        patientContact: "9827136183",
        appointmentType: "Consultation",
        status: "Cancelled",
        doctorNotes: "Patient canceled the appointment.",
    },
    {
        patientName: "Ava Brown",
        appointmentDate: "2024-09-03",
        appointmentTime: "04:00 PM",
        patientContact: "9827137193",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient reports chest pain.",
    },
    {
        patientName: "Liam Wilson",
        appointmentDate: "2024-09-03",
        appointmentTime: "05:00 PM",
        patientContact: "9827138203",
        appointmentType: "Check-up",
        status: "Completed",
        doctorNotes: "Routine check-up, no issues reported.",
    },
    {
        patientName: "Emily Davis",
        appointmentDate: "2024-09-03",
        appointmentTime: "06:00 PM",
        patientContact: "9827139213",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient experiencing back pain.",
    },
    {
        patientName: "Lucas Martin",
        appointmentDate: "2024-09-04",
        appointmentTime: "10:00 AM",
        patientContact: "9827140223",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient's recovery from surgery.",
    },
    {
        patientName: "Ella Garcia",
        appointmentDate: "2024-09-04",
        appointmentTime: "11:00 AM",
        patientContact: "9827141233",
        appointmentType: "Consultation",
        status: "Rescheduled",
        doctorNotes: "Patient reports fatigue and dizziness.",
    },
    {
        patientName: "Henry Martinez",
        appointmentDate: "2024-09-04",
        appointmentTime: "12:00 PM",
        patientContact: "9827142243",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient has a persistent cough.",
    },
    {
        patientName: "Olivia Hernandez",
        appointmentDate: "2024-09-04",
        appointmentTime: "01:00 PM",
        patientContact: "9827143253",
        appointmentType: "Check-up",
        status: "Completed",
        doctorNotes: "Routine check-up, patient is in good health.",
    },
    {
        patientName: "Alexander White",
        appointmentDate: "2024-09-04",
        appointmentTime: "02:00 PM",
        patientContact: "9827144263",
        appointmentType: "Consultation",
        status: "Cancelled",
        doctorNotes: "Patient canceled due to personal reasons.",
    },
    {
        patientName: "Sophia Thompson",
        appointmentDate: "2024-09-04",
        appointmentTime: "03:00 PM",
        patientContact: "9827145273",
        appointmentType: "Follow-up",
        status: "Scheduled",
        doctorNotes: "Patient recovering from an injury.",
    },
    {
        patientName: "Benjamin Moore",
        appointmentDate: "2024-09-04",
        appointmentTime: "04:00 PM",
        patientContact: "9827146283",
        appointmentType: "Consultation",
        status: "Completed",
        doctorNotes: "Patient reports improvement in symptoms.",
    },
    {
        patientName: "Charlotte Taylor",
        appointmentDate: "2024-09-04",
        appointmentTime: "05:00 PM",
        patientContact: "9827147293",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient has a skin rash.",
    },
    {
        patientName: "Sebastian Lewis",
        appointmentDate: "2024-09-04",
        appointmentTime: "06:00 PM",
        patientContact: "9827148303",
        appointmentType: "Check-up",
        status: "Rescheduled",
        doctorNotes: "Routine check-up rescheduled by patient.",
    },
    {
        patientName: "Amelia Clark",
        appointmentDate: "2024-09-05",
        appointmentTime: "10:00 AM",
        patientContact: "9827149313",
        appointmentType: "Consultation",
        status: "Scheduled",
        doctorNotes: "Patient reports insomnia and anxiety.",
    },
    {
        patientName: "Matthew Young",
        appointmentDate: "2024-09-05",
        appointmentTime: "11:00 AM",
        patientContact: "9827150323",
        appointmentType: "Follow-up",
        status: "Completed",
        doctorNotes: "Follow-up on medication effectiveness.",
    },
];

export const medicalHistory = [
    {
        date: "2022-08-22",
        condition: "Gastritis",
        diagnosis: "Acute Gastritis",
        doctor: "Dr. Linda Taylor",
        status: "Resolved",
        notes:
            "Patient advised to avoid spicy foods; symptoms resolved after treatment.",
    },
    {
        date: "2022-05-30",
        condition: "Anemia",
        diagnosis: "Iron-Deficiency Anemia",
        doctor: "Dr. Kevin Anderson",
        status: "Resolved",
        notes: "Patient prescribed iron supplements; hemoglobin levels normalized.",
    },
    {
        date: "2022-03-14",
        condition: "High Cholesterol",
        diagnosis: "Hyperlipidemia",
        doctor: "Dr. Angela Martinez",
        status: "Ongoing",
        notes: "Patient advised on dietary changes; prescribed statins.",
    },
    {
        date: "2021-12-01",
        condition: "Depression",
        diagnosis: "Major Depressive Disorder",
        doctor: "Dr. David Clark",
        status: "Ongoing",
        notes: "Patient undergoing therapy and taking antidepressants.",
    },
    {
        date: "2021-09-18",
        condition: "Back Pain",
        diagnosis: "Mechanical Back Pain",
        doctor: "Dr. James Wilson",
        status: "Resolved",
        notes: "Patient recovered after physiotherapy sessions.",
    },
];

export const allergiesData = [
    {
        allergen: "Peanuts",
        reactionType: "Anaphylaxis",
        severity: "Severe",
        dateIdentified: "2022-03-15",
        notes: "Carry an EpiPen at all times.",
    },
    {
        allergen: "Shellfish",
        reactionType: "Hives",
        severity: "Moderate",
        dateIdentified: "2021-06-10",
        notes: "Avoid all types of shellfish.",
    },
    {
        allergen: "Penicillin",
        reactionType: "Rash",
        severity: "Mild",
        dateIdentified: "2020-12-01",
        notes: "Alternative antibiotics are required.",
    },
    {
        allergen: "Dust mites",
        reactionType: "Sneezing",
        severity: "Mild",
        dateIdentified: "2019-11-22",
        notes: "Use hypoallergenic bedding.",
    },
    {
        allergen: "Pollen",
        reactionType: "Watery Eyes",
        severity: "Mild",
        dateIdentified: "2018-04-05",
        notes: "Take antihistamines during spring.",
    },
];

export const pastSurgeries = [
    {
        date: "2019-03-25",
        name: "Hernia Repair",
        surgeon: "Dr. Nitin Gupta",
        hospital: "Columbia Asia Hospital",
        outcome: "Successful",
        notes: "Discharged on the same day.",
    },
    {
        date: "2022-01-10",
        name: "Coronary Artery Bypass Grafting",
        surgeon: "Dr. Sunil Verma",
        hospital: "Narayana Health",
        outcome: "Successful",
        notes: "Regular cardiac check-ups advised.",
    },
    {
        date: "2016-09-15",
        name: "Tonsillectomy",
        surgeon: "Dr. Priya Das",
        hospital: "Manipal Hospital",
        outcome: "Successful",
        notes: "Slight throat irritation post-surgery.",
    },
    {
        date: "2023-03-05",
        name: "Thyroidectomy",
        surgeon: "Dr. Ravi Patel",
        hospital: "Fortis Hospital",
        outcome: "Successful",
        notes: "Hormone replacement therapy started.",
    },
    {
        date: "2020-07-19",
        name: "Spinal Fusion",
        surgeon: "Dr. Sameer Malhotra",
        hospital: "Artemis Hospital",
        outcome: "Successful",
        notes: "Regular physiotherapy sessions required.",
    },
];

export const pastConsultations = [
    {
        date: "2021-05-12",
        hospital: "Apollo Hospital",
        surgeon: "Dr. Rajesh Kumar",
        speciality: "Orthopedics",
        symptoms: "Severe back pain",
        diagnosis: "Herniated disc",
        notes: "Recommended physiotherapy and pain management",
    },
    {
        date: "2020-08-20",
        hospital: "Fortis Hospital",
        surgeon: "Dr. Meera Joshi",
        speciality: "Cardiology",
        symptoms: "Shortness of breath, chest pain",
        diagnosis: "Mild angina",
        notes: "Advised lifestyle changes and medication",
    },
    {
        date: "2022-01-15",
        hospital: "Max Healthcare",
        surgeon: "Dr. Piyush Sharma",
        speciality: "Dermatology",
        symptoms: "Severe acne",
        diagnosis: "Cystic acne",
        notes: "Prescribed topical and oral antibiotics",
    },
    {
        date: "2023-04-03",
        hospital: "Manipal Hospital",
        surgeon: "Dr. Ayesha Singh",
        speciality: "Neurology",
        symptoms: "Frequent headaches, dizziness",
        diagnosis: "Migraine",
        notes: "Recommended migraine management plan and medication",
    },
    {
        date: "2019-11-18",
        hospital: "AIIMS",
        surgeon: "Dr. Suresh Nair",
        speciality: "Gastroenterology",
        symptoms: "Stomach pain, bloating",
        diagnosis: "Irritable Bowel Syndrome (IBS)",
        notes: "Prescribed dietary changes and probiotics",
    },
    {
        date: "2021-10-25",
        hospital: "Kokilaben Hospital",
        surgeon: "Dr. Nisha Patil",
        speciality: "Pulmonology",
        symptoms: "Chronic cough, difficulty breathing",
        diagnosis: "Bronchitis",
        notes: "Antibiotics prescribed; follow-up recommended",
    },
];

export interface PatientSample {
    uuid: string;
    fullName: string;
    age: number;
    gender: string;
    phone: string;
    email: string;
    bloodGroup: string;
    address: string;
}

export const patients: PatientSample[] = [
    {
        uuid: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
        fullName: "Aarav Sharma",
        age: 34,
        gender: "Male",
        phone: "9123456789",
        email: "aarav.sharma@example.com",
        bloodGroup: "A+",
        address: "Delhi, India",
    },
    {
        uuid: "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
        fullName: "Diya Patel",
        age: 29,
        gender: "Female",
        phone: "9123456790",
        email: "diya.patel@example.com",
        bloodGroup: "B+",
        address: "Mumbai, India",
    },
    {
        uuid: "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
        fullName: "Vivaan Gupta",
        age: 42,
        gender: "Male",
        phone: "9123456791",
        email: "vivaan.gupta@example.com",
        bloodGroup: "O+",
        address: "Bangalore, India",
    },
    {
        uuid: "4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9g",
        fullName: "Anika Singh",
        age: 27,
        gender: "Female",
        phone: "9123456792",
        email: "anika.singh@example.com",
        bloodGroup: "AB+",
        address: "Kolkata, India",
    },
    {
        uuid: "5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9g0h",
        fullName: "Kabir Rao",
        age: 37,
        gender: "Male",
        phone: "9123456793",
        email: "kabir.rao@example.com",
        bloodGroup: "A-",
        address: "Hyderabad, India",
    },
    {
        uuid: "6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9g0h1i",
        fullName: "Isha Verma",
        age: 31,
        gender: "Female",
        phone: "9123456794",
        email: "isha.verma@example.com",
        bloodGroup: "B-",
        address: "Chennai, India",
    },
    {
        uuid: "7a8b9c0d-1e2f-3a4b-5c6d-7e8f9g0h1i2j",
        fullName: "Arjun Mehta",
        age: 45,
        gender: "Male",
        phone: "9123456795",
        email: "arjun.mehta@example.com",
        bloodGroup: "O-",
        address: "Pune, India",
    },
    {
        uuid: "8b9c0d1e-2f3a-4b5c-6d7e-8f9g0h1i2j3k",
        fullName: "Sana Desai",
        age: 26,
        gender: "Female",
        phone: "9123456796",
        email: "sana.desai@example.com",
        bloodGroup: "AB-",
        address: "Ahmedabad, India",
    },
    {
        uuid: "9c0d1e2f-3a4b-5c6d-7e8f-9g0h1i2j3k4l",
        fullName: "Rohan Iyer",
        age: 39,
        gender: "Male",
        phone: "9123456797",
        email: "rohan.iyer@example.com",
        bloodGroup: "A+",
        address: "Surat, India",
    },
    {
        uuid: "0d1e2f3a-4b5c-6d7e-8f9g-0h1i2j3k4l5m",
        fullName: "Mira Kumar",
        age: 33,
        gender: "Female",
        phone: "9123456798",
        email: "mira.kumar@example.com",
        bloodGroup: "B+",
        address: "Jaipur, India",
    },
    {
        uuid: "1e2f3a4b-5c6d-7e8f-9g0h-1i2j3k4l5m6n",
        fullName: "Ayaan Sinha",
        age: 48,
        gender: "Male",
        phone: "9123456799",
        email: "ayaan.sinha@example.com",
        bloodGroup: "O+",
        address: "Lucknow, India",
    },
    {
        uuid: "2f3a4b5c-6d7e-8f9g-0h1i-2j3k4l5m6n7o",
        fullName: "Tara Bajaj",
        age: 22,
        gender: "Female",
        phone: "9123456710",
        email: "tara.bajaj@example.com",
        bloodGroup: "AB+",
        address: "Bhopal, India",
    },
    {
        uuid: "3a4b5c6d-7e8f-9g0h-1i2j-3k4l5m6n7o8p",
        fullName: "Vikram Joshi",
        age: 52,
        gender: "Male",
        phone: "9123456711",
        email: "vikram.joshi@example.com",
        bloodGroup: "A-",
        address: "Patna, India",
    },
    {
        uuid: "4b5c6d7e-8f9g-0h1i-2j3k-4l5m6n7o8p9q",
        fullName: "Nisha Pandey",
        age: 28,
        gender: "Female",
        phone: "9123456712",
        email: "nisha.pandey@example.com",
        bloodGroup: "B-",
        address: "Guwahati, India",
    },
    {
        uuid: "5c6d7e8f-9g0h-1i2j-3k4l-5m6n7o8p9q0r",
        fullName: "Harsh Kapoor",
        age: 36,
        gender: "Male",
        phone: "9123456713",
        email: "harsh.kapoor@example.com",
        bloodGroup: "O-",
        address: "Chandigarh, India",
    },
    {
        uuid: "6d7e8f9g-0h1i-2j3k-4l5m-6n7o8p9q0r1s",
        fullName: "Riya Thakur",
        age: 24,
        gender: "Female",
        phone: "9123456714",
        email: "riya.thakur@example.com",
        bloodGroup: "AB-",
        address: "Kochi, India",
    },
    {
        uuid: "7e8f9g0h-1i2j-3k4l-5m6n-7o8p9q0r1s2t",
        fullName: "Dev Patel",
        age: 44,
        gender: "Male",
        phone: "9123456715",
        email: "dev.patel@example.com",
        bloodGroup: "A+",
        address: "Nagpur, India",
    },
    {
        uuid: "8f9g0h1i-2j3k-4l5m-6n7o-8p9q0r1s2t3u",
        fullName: "Sanya Chawla",
        age: 30,
        gender: "Female",
        phone: "9123456716",
        email: "sanya.chawla@example.com",
        bloodGroup: "B+",
        address: "Indore, India",
    },
    {
        uuid: "9g0h1i2j-3k4l-5m6n-7o8p-9q0r1s2t3u4v",
        fullName: "Raj Malhotra",
        age: 41,
        gender: "Male",
        phone: "9123456717",
        email: "raj.malhotra@example.com",
        bloodGroup: "O+",
        address: "Ranchi, India",
    },
    {
        uuid: "0h1i2j3k-4l5m-6n7o-8p9q-0r1s2t3u4v5w",
        fullName: "Pooja Nair",
        age: 35,
        gender: "Female",
        phone: "9123456718",
        email: "pooja.nair@example.com",
        bloodGroup: "AB+",
        address: "Vadodara, India",
    },
    {
        uuid: "1i2j3k4l-5m6n-7o8p-9q0r-1s2t3u4v5w6x",
        fullName: "Kunal Agarwal",
        age: 38,
        gender: "Male",
        phone: "9123456719",
        email: "kunal.agarwal@example.com",
        bloodGroup: "A-",
        address: "Mysore, India",
    },
    {
        uuid: "2j3k4l5m-6n7o-8p9q-0r1s-2t3u4v5w6x7y",
        fullName: "Shreya Roy",
        age: 32,
        gender: "Female",
        phone: "9123456720",
        email: "shreya.roy@example.com",
        bloodGroup: "B-",
        address: "Amritsar, India",
    },
    {
        uuid: "3k4l5m6n-7o8p-9q0r-1s2t-3u4v5w6x7y8z",
        fullName: "Ankit Reddy",
        age: 43,
        gender: "Male",
        phone: "9123456721",
        email: "ankit.reddy@example.com",
        bloodGroup: "O-",
        address: "Agra, India",
    },
];

export const prescriptions: Prescription[] = [
    {
        id: 1,
        medication: "Aspirin",
        dosage: "100mg",
        duration: "14 days",
    },
    {
        id: 2,
        medication: "Ibuprofen",
        dosage: "200mg",
        duration: "10 days",
    },
    {
        id: 3,
        medication: "Amoxicillin",
        dosage: "500mg",
        duration: "7 days",
    },
    {
        id: 4,
        medication: "Lisinopril",
        dosage: "10mg",
        duration: "30 days",
    },
    {
        id: 5,
        medication: "Metformin",
        dosage: "500mg",
        duration: "90 days",
    },
    {
        id: 6,
        medication: "Atorvastatin",
        dosage: "20mg",
        duration: "60 days",
    },
    {
        id: 7,
        medication: "Omeprazole",
        dosage: "40mg",
        duration: "14 days",
    },
    {
        id: 8,
        medication: "Levothyroxine",
        dosage: "75mcg",
        duration: "30 days",
    },
    {
        id: 9,
        medication: "Gabapentin",
        dosage: "300mg",
        duration: "21 days",
    },
    {
        id: 10,
        medication: "Losartan",
        dosage: "50mg",
        duration: "30 days",
    },
];

export const medicines: Medicine[] = [
    {id: 1, name: "Aspirin", isHarmfulWith: ["Ibuprofen", "Clopidogrel"]},
    {id: 2, name: "Ibuprofen", isHarmfulWith: ["Aspirin", "Warfarin"]},
    {id: 3, name: "Paracetamol", isHarmfulWith: []},
    {
        id: 4,
        name: "Atorvastatin (Lipikind)",
        isHarmfulWith: ["Erythromycin", "Clarithromycin"],
    },
    {
        id: 5,
        name: "Clopidogrel (Clopivas)",
        isHarmfulWith: ["Aspirin", "Omeprazole"],
    },
    {id: 6, name: "Amoxicillin (Mox)", isHarmfulWith: ["Methotrexate"]},
    {id: 7, name: "Cetirizine (Cetzine)", isHarmfulWith: ["Theophylline"]},
    {
        id: 8,
        name: "Metformin (Glyciphage)",
        isHarmfulWith: ["Cimetidine", "Furosemide"],
    },
    {id: 9, name: "Pantoprazole (Pantocid)", isHarmfulWith: ["Methotrexate"]},
    {id: 10, name: "Losartan (Repace)", isHarmfulWith: ["Lithium", "Aspirin"]},
    {id: 11, name: "Amlodipine (Amlong)", isHarmfulWith: ["Simvastatin"]},
    {
        id: 12,
        name: "Levothyroxine (Thyronorm)",
        isHarmfulWith: ["Calcium Supplements", "Iron Supplements"],
    },
    {
        id: 13,
        name: "Dicyclomine (Cyclopam)",
        isHarmfulWith: ["Aspirin", "Ibuprofen"],
    },
    {id: 14, name: "Ranitidine (Rantac)", isHarmfulWith: ["Warfarin"]},
    {
        id: 15,
        name: "Azithromycin (Azee)",
        isHarmfulWith: ["Warfarin", "Digoxin"],
    },
    {
        id: 16,
        name: "Simvastatin (Simvotin)",
        isHarmfulWith: ["Grapefruit Juice", "Amlodipine"],
    },
    {
        id: 17,
        name: "Hydrochlorothiazide (Hydrazide)",
        isHarmfulWith: ["Lithium", "NSAIDs"],
    },
    {
        id: 18,
        name: "Furosemide (Lasix)",
        isHarmfulWith: ["Aminoglycosides", "Digoxin"],
    },
    {
        id: 19,
        name: "Warfarin (Marevan)",
        isHarmfulWith: ["Aspirin", "Ibuprofen", "Azithromycin"],
    },
    {
        id: 20,
        name: "Lisinopril (Lisotec)",
        isHarmfulWith: ["Potassium Supplements", "NSAIDs"],
    },
    {
        id: 21,
        name: "Spironolactone (Aldactone)",
        isHarmfulWith: ["Potassium Supplements", "ACE Inhibitors"],
    },
    {id: 22, name: "Omeprazole (Omez)", isHarmfulWith: ["Clopidogrel"]},
    {
        id: 23,
        name: "Chlorpheniramine (Cetrizine)",
        isHarmfulWith: ["Alcohol", "Sedatives"],
    },
    {
        id: 24,
        name: "Dexamethasone (Dexona)",
        isHarmfulWith: ["Anticoagulants", "Aspirin"],
    },
    {
        id: 25,
        name: "Digoxin (Lanoxin)",
        isHarmfulWith: ["Amiodarone", "Verapamil"],
    },
    {
        id: 26,
        name: "Verapamil (Calaptin)",
        isHarmfulWith: ["Beta Blockers", "Digoxin"],
    },
    {
        id: 27,
        name: "Erythromycin (Eromycin)",
        isHarmfulWith: ["Statins", "Atorvastatin"],
    },
    {id: 28, name: "Salmeterol (Serevent)", isHarmfulWith: ["Beta Blockers"]},
    {
        id: 29,
        name: "Ciprofloxacin (Cifran)",
        isHarmfulWith: ["Theophylline", "Antacids"],
    },
    {id: 30, name: "Levofloxacin (Levoflox)", isHarmfulWith: ["NSAIDs"]},
    {
        id: 31,
        name: "Prednisolone (Omnacortil)",
        isHarmfulWith: ["NSAIDs", "Anticoagulants"],
    },
    {
        id: 32,
        name: "Methotrexate (Trexall)",
        isHarmfulWith: ["NSAIDs", "Amoxicillin"],
    },
    {
        id: 33,
        name: "Glibenclamide (Glyburide)",
        isHarmfulWith: ["Rifampicin", "Diuretics"],
    },
    {
        id: 34,
        name: "Doxycycline (Doxy-1)",
        isHarmfulWith: ["Antacids", "Iron Supplements"],
    },
    {
        id: 35,
        name: "Clarithromycin (Biaxin)",
        isHarmfulWith: ["Statins", "Digoxin"],
    },
    {id: 36, name: "Telmisartan (Telma)", isHarmfulWith: ["NSAIDs", "Lithium"]},
    {id: 37, name: "Gliclazide (Diamicron)", isHarmfulWith: ["Alcohol"]},
    {
        id: 38,
        name: "Ondansetron (Emeset)",
        isHarmfulWith: ["Tramadol", "SSRIs"],
    },
    {
        id: 39,
        name: "Carvedilol (Cardivas)",
        isHarmfulWith: ["Verapamil", "Digoxin"],
    },
    {
        id: 40,
        name: "Metoprolol (Metolar)",
        isHarmfulWith: ["Verapamil", "Amlodipine"],
    },
];
